spring:
  datasource:
    url: jdbc:mysql:aws://my-aurora-cluster.cluster-cnmw32yasadf.ap-northeast-1.rds.amazonaws.com/hello
    driver-class-name: software.aws.rds.jdbc.mysql.Driver
    password: ${password}
    username: admin
  flyway:
    enabled: true
